/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantsRouteImport } from './routes/restaurants'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventNameRouteImport } from './routes/events/$eventName'

const RestaurantsRoute = RestaurantsRouteImport.update({
  id: '/restaurants',
  path: '/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventNameRoute = EventsEventNameRouteImport.update({
  id: '/events/$eventName',
  path: '/events/$eventName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRoute
  '/events/$eventName': typeof EventsEventNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRoute
  '/events/$eventName': typeof EventsEventNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/restaurants': typeof RestaurantsRoute
  '/events/$eventName': typeof EventsEventNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/restaurants' | '/events/$eventName'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/restaurants' | '/events/$eventName'
  id: '__root__' | '/' | '/restaurants' | '/events/$eventName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RestaurantsRoute: typeof RestaurantsRoute
  EventsEventNameRoute: typeof EventsEventNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurants': {
      id: '/restaurants'
      path: '/restaurants'
      fullPath: '/restaurants'
      preLoaderRoute: typeof RestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventName': {
      id: '/events/$eventName'
      path: '/events/$eventName'
      fullPath: '/events/$eventName'
      preLoaderRoute: typeof EventsEventNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RestaurantsRoute: RestaurantsRoute,
  EventsEventNameRoute: EventsEventNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
